apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: gitops-master
  namespace: default
spec:
  parameters:
    id: gitops-master
    region: eu-west-1
    version: "1.27"
    nodes:
      count: 3
      size: small
    serviceSelector: gitops-master
    gitops:
      url: https://github.com/djeremiah/cluster-hub-gitops
      kubeConfigSecretRef:
        name: mcp-cluster-hub-kubeconfig
        namespace: default
  writeConnectionSecretToRef:
    name: aws-gitops-master-kubeconfig
