apiVersion: mcp.caas.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: cluster-hub
  namespace: default
spec:
  parameters:
    organizationName: crossplane-by-example
    configuration: cluster-as-a-service
  writeConnectionSecretToRef:
    name: mcp-cluster-hub-kubeconfig
