apiVersion: mcp.caas.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: qbr-demo
  namespace: default
spec:
  parameters:
    organizationName: crossplane-by-example
    configuration: caas-toolkit
  writeConnectionSecretToRef:
    name: mcp-qbr-demo-kubeconfig
